# Generated by Django 4.2.6 on 2023-10-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Login",
        ),
    ]
