# Generated by Django 4.2.6 on 2023-10-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_rename_product_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="name",
        ),
        migrations.AddField(
            model_name="login",
            name="pw",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="id",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
